server:
  port: 19083

spring:
  application:
    name: product-service

  config:
    import: "configserver:"      # Config Server에서 설정 가져옴
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        max-attempts: 3
        initial-interval: 1000
